name: Run Mypy

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.2]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install requirements including mypy
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install mypy  # Ensure mypy is installed
          python -m pip list

      # Run mypy
      - name: Run mypy
        run: |
          mypy .
